### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by this-is-fine-dev** [Bahlor/jQuery-Pixel-Related-Object-Selection#3]
I got an error message in chrome console: 
Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.

**Comment by Bahlor** [comment]
This is actually not an issue related to this project. It seems like you're trying to get an image from a different server, this is normally prevented by a browser based on the Cross Domain Policy. 

Have a look over here: https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

Make sure that the other server has CORS (Cross Origin Ressource Sharing) activated, otherwise the access from different domains is restricted.
